server:
  port: 8080

spring:
  application:
    name: api
  profiles:
    active: dev
    web:
      resources:
        add-mappings: 'false'
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      pazzword: 12345678
  jpa:
    show-sql: true
    hibernate: ddl-auto
logging:
  level:
    org:
      springframework: DEBUG
#    root: INFO
#Jasypt
jasypt:
  encryptor:
    bean: EncryptorBean
management:
  endpoints:
    web:
      exposure:
        include: mappings
taiwanDollar:
  baseUrl: https://apisvc-test.tcbbank.com.tw/tcbbank/private/TWS/ESB/TWTXN/
  baseUrl2: https://apisvc-test.tcbbank.com.tw/tcbbank/private/TWS/ESB/TW/
db1:
  datasource:
    url: jdbc:mariadb://localhost:3306/db1
    jdbcurl: jdbc:mariadb://localhost:3306/db1
    driverClassName:  org.mariadb.jdbc.Driver
    username: user
    pazzword: 1qaz2wsx
db2:
  datasource:
    url: jdbc:mariadb://localhost:3306/db2
    jdbcurl: jdbc:mariadb://localhost:3306/db2
    driverClassName:  org.mariadb.jdbc.Driver
    username: user
    pazzword: 1qaz2wsx

ib:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=IB;encrypt=false
    jdbcurl: jdbc:sqlserver://localhost:1433;databaseName=IB;encrypt=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    pazzword: 1qaz2wsx
    maximumPoolSize: 6